### ISSUE TITLE
Error: Minimum builderFeatures required: { persistentOutputFlag: true }

### ISSUE THREAD

**Issue by sriram-viswanathan** [ember-cli/broccoli-lint-eslint#128]
Getting the following error while trying to run `ember build`

package.json
```
"devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "broccoli-merge-trees": "2.0.0",
    "broccoli-lint-eslint": "4.2.1", // --> used this to try and fix this error, doesn't fix
    "broccoli-static-compiler": "^0.2.2",
},
```

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: Minimum builderFeatures required: { persistentOutputFlag: true }
    at LessCompiler.Plugin._checkBuilderFeatures (<path>/node_modules/broccoli-less-single/node_modules/broccoli-plugin/index.js:62:11)
    at LessCompiler.Plugin.__broccoliGetInfo__ (<path>/node_modules/broccoli-less-single/node_modules/broccoli-plugin/index.js:45:8)
    at getPluginName (<path>/node_modules/broccoli-builder/lib/builder.js:291:23)
    at new Node (<path>/node_modules/broccoli-builder/lib/builder.js:260:11)
    at readAndReturnNodeFor (<path>/node_modules/broccoli-builder/lib/builder.js:112:16)
    at <path>/node_modules/broccoli-builder/lib/builder.js:151:24
    at tryCatch (<path>/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (<path>/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:538:13)
    at <path>/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (<path>/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)

  - codeFrame: Minimum builderFeatures required: { persistentOutputFlag: true }
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `BroccoliMergeTrees` plugin. 💥
Minimum builderFeatures required: { persistentOutputFlag: true }
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `BroccoliMergeTrees` plugin. 💥
Minimum builderFeatures required: { persistentOutputFlag: true }
  - name: Error
  - nodeAnnotation: BroccoliMergeTrees
  - nodeName: BroccoliMergeTrees
  - originalErrorMessage: Minimum builderFeatures required: { persistentOutputFlag: true }
  - stack: Error: Minimum builderFeatures required: { persistentOutputFlag: true }
    at LessCompiler.Plugin._checkBuilderFeatures (<path>/node_modules/broccoli-less-single/node_modules/broccoli-plugin/index.js:62:11)
    at LessCompiler.Plugin.__broccoliGetInfo__ (<path>/node_modules/broccoli-less-single/node_modules/broccoli-plugin/index.js:45:8)
    at getPluginName (<path>/node_modules/broccoli-builder/lib/builder.js:291:23)
    at new Node (<path>/node_modules/broccoli-builder/lib/builder.js:260:11)
    at readAndReturnNodeFor (<path>/node_modules/broccoli-builder/lib/builder.js:112:16)
    at <path>/node_modules/broccoli-builder/lib/builder.js:151:24
    at tryCatch (<path>/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (<path>/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:538:13)
    at <path>/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (<path>/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11
```

Can someone help me out here with some pointers?

**Comment by fenichelar** [comment]
Travis?

**Comment by sriram-viswanathan** [comment]
Nope, using a internal build tool from my organization. Sadly cannot share that link as its on corp network.

Finding: This happens when there are some nested dependent packages which are using `less` compiler mixed with `scss` compiler

I was able to fix this error by removing that package which was depending on less -> `ember-cli-bar-view`

**Comment by sriram-viswanathan** [comment]
Feel free to close this issue if you feel its no longer valid

**Comment by oozusta** [comment]
I have the same issue, haven't yet been able to resolve it. Started getting it after the latest 'patch' of broccoli-builder:
https://github.com/ember-cli/broccoli-builder

**Comment by fenichelar** [comment]
I only have this issue on Travis, it works fine on my Mac. It just started.

**Comment by fenichelar** [comment]
@oozusta `npm update` fixed it for me:
```
-    "ember-cli-eslint": "^4.2.1",
+    "ember-cli-eslint": "^4.2.3",
-    "eslint-plugin-ember": "^5.0.0",
+    "eslint-plugin-ember": "^5.2.0",
```

**Comment by rwjblue** [comment]
Thanks all, and sorry for the issue!
